cspn:
  num_leaves: 10
  num_nodes: 8
  nn_hidden_dim: 64
  nn_num_hidden_layers: 2

# TODO add pretrained section for autoencoder

dataset:
  name: mnist
  channels: 3
  width: 28
  height: 28
  num_classes: 10

training:
  epochs: 1
  learning_rate: 0.001
  batch_size: 32
  beta_start: 0.0
  beta_end: 1.0
  beta_anneal_epochs: 25

wandb:
  mode: disabled
  project: master-thesis
  entity: jmartini-tu-darmstadt

paths:
  autoencoder: "checkpoints/autoencoder/mnist.pt"
  cspn: "checkpoints/cspn/mnist.pt"

seed: null
