services:
  train:
    build:
      context: .
      dockerfile: Dockerfile
    image: ciglspc:latest
    # devices:
    #  - nvidia.com/gpu=all
    volumes:
      - ./:/app
    entrypoint: ["/opt/venv/bin/python", "main.py"]
    command: ["$HYDRA_ARGS"]
