services:
  train-autoencoder:
    build:
      context: .
      dockerfile: Dockerfile
    image: ciglspc:latest
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ./:/app
    entrypoint: ["/opt/venv/bin/python", "train_autoencoder.py"]
    command: ["$HYDRA_ARGS"]

  train-cspn:
    build:
      context: .
      dockerfile: Dockerfile
    image: ciglspc:latest
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ./:/app
    entrypoint: ["/opt/venv/bin/python", "train_cspn.py"]
    command: ["$HYDRA_ARGS"]

  inference:
    build:
      context: .
      dockerfile: Dockerfile
    image: ciglspc:latest
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ./:/app
    entrypoint: ["/opt/venv/bin/python", "inference.py"]
    command: ["$HYDRA_ARGS"]
