autoencoder:
  model_type: variational
  latent_dim: 16
  base_channels: 32
  num_blocks: 2
  res_blocks: 1

dataset:
  name: mnist
  channels: 1
  width: 28
  height: 28
  num_classes: 10

training:
  epochs: 1
  learning_rate: 0.001
  batch_size: 32
  beta_start: 0.0
  beta_end: 1.0
  beta_anneal_epochs: 25

wandb:
  mode: disabled
  project: master-thesis
  entity: jmartini-tu-darmstadt

paths:
  autoencoder: "checkpoints/autoencoder/mnist_test.pt"

seed: null
