type: cspn

dataset:
  name: celeba_single_attribute
  channels: 3
  height: 64
  width: 64
  num_classes: 2

autoencoder:
  name: "autoencoder_celeba"
  external: false

model:
  model_type: "psinet"
  num_vars: 128
  num_repetitions: 5
  num_input_distributions: 8
  num_sums: 8
  min_var: 0.001
  max_var: 1.0
  h_dims: [ 128 ]

training:
  epochs: 100
  learning_rate: 0.001
  batch_size: 32

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt