cspn:
  model_type: "psinet"
  num_leaves: 10
  num_sums: 10
  depth: 3
  num_repetitions: 1
  nn_hidden_dim: 64
  nn_num_hidden_layers: 2

# TODO add pretrained section for autoencoder

dataset:
  name: flowers102
  channels: 3
  width: 128
  height: 128
  num_classes: 102

training:
  epochs: 150
  learning_rate: 0.001
  batch_size: 32


wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt

paths:
  autoencoder: "checkpoints/autoencoder/flowers.pt"
  cspn: "checkpoints/cspn/flowers_custom.pt"

seed: null
