type: cspn

dataset:
  name: flowers102
  channels: 3
  height: 64
  width: 64
  num_classes: 102

autoencoder:
  name: "autoencoder_flowers102"
  external: false
  latent_dim: 128

model:
  model_type: "psinet"
  num_repetitions: 5
  num_input_distributions: 16
  num_sums: 16
  min_var: 0.001
  max_var: 1.0
  h_dims: [ 128, 128 ]

training:
  epochs: 1
  learning_rate: 0.001
  batch_size: 128

wandb:
  mode: disabled
  project: master-thesis
  entity: jmartini-tu-darmstadt