type: cspn

dataset:
  name: mnist

autoencoder:
  name: "autoencoder_mnist"
  external: false

model:
  model_type: "psinet"
  num_vars: 16
  num_repetitions: 3
  num_input_distributions: 8
  num_sums: 8
  min_var: 0.001
  max_var: 4.0
  h_dims: [ 256, 128 ]
  encoder_config:
    encoder_type: categorical
    num_classes: [ 10 ]

training:
  epochs: 200
  learning_rate: 0.0003
  batch_size: 128
  early_stopping_patience: 10
  early_stopping_min_delta: 0.01
