cspn:
  model_type: "custom"
  num_leaves: 10
  num_sums: 32
  depth: 3
  num_repetitions: 1
  nn_hidden_dim: 64
  nn_num_hidden_layers: 1

# TODO add pretrained section for autoencoder

dataset:
  name: mnist
  channels: 3
  width: 28
  height: 28
  num_classes: 10

training:
  epochs: 150
  learning_rate: 0.001
  batch_size: 512


wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt

paths:
  autoencoder: "checkpoints/autoencoder/mnist.pt"
  cspn: "checkpoints/cspn/mnist_custom.pt"

seed: null
