name: autoencoder
training:
  epochs: ${train.autoencoder.epochs}
  batch_size: ${train.autoencoder.batch_size}
  learning_rate: ${optimization.autoencoder.learning_rate}
  latent_size: ${train.autoencoder.latent_size}
