epochs: ${optimization.cspn.epochs}
learning_rate: ${optimization.cspn.learning_rate}
label_embedding_dim: ${optimization.cspn.label_embedding_dim}
context_hidden_dim: ${optimization.cspn.context_hidden_dim}
context_num_layers: ${optimization.cspn.context_num_layers}
num_mixture_components: ${optimization.cspn.num_mixture_components}
num_sum_components: ${optimization.cspn.num_sum_components}
label_mode: dataset
