defaults:
  - autoencoder: default
  - cspn: default
  - inference: default
  - dataset: mnist
  - training: default
  - _self_

# TODO change training mode to train_cspn
mode: train_cspn

seed: null

# TODO update paths
paths:
  ae_checkpoint: null
  cspn_checkpoint: null
