type: ae

dataset:
  name: celeba
  channels: 3
  width: 64
  height: 64
  num_classes: 2

model:
  model_type: variational
  latent_dim: 128
  num_blocks: 4
  base_channels: 64

training:
  epochs: 200
  learning_rate: 0.0001
  batch_size: 256
  beta: 1.0
  kl_warmup_epochs: 50

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt
