type: ae

dataset:
  name: colour_mnist

model:
  model_type: variational
  latent_dim: 16
  num_blocks: 2
  base_channels: 32

training:
  vae_type: beta
  epochs: 100
  learning_rate: 0.0005
  batch_size: 128
  beta: 1.0
  beta_start: 0.0
  beta_end: 1.0
  kl_warmup_epochs: 10
  lambda_perceptual: 0.0

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt