type: ae

dataset:
  name: cub200

model:
  model_type: variational
  latent_dim: 256
  num_blocks: 3
  base_channels: 64

training:
  epochs: 200
  learning_rate: 0.0005
  batch_size: 64
  beta: 1.0
  kl_warmup_epochs: 20

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt