autoencoder:
  model_type: variational
  latent_dim: 128
  base_channels: 64
  num_blocks: 3
  res_blocks: 2

dataset:
  name: cub200
  channels: 3
  width: 128
  height: 128
  num_classes: 200

training:
  epochs: 200
  learning_rate: 0.0003
  batch_size: 64
  beta_start: 0.0
  beta_end: 0.5
  beta_anneal_epochs: 150

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt

paths:
  autoencoder: "checkpoints/autoencoder/cub200.pt"

seed: null
