type: ae

dataset:
  name: cub200

model:
  model_type: variational
  latent_dim: 256
  num_blocks: 3

training:
  epochs: 200
  learning_rate: 0.0005
  batch_size: 64
  beta: 8.0

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt