type: ae

dataset:
  name: flowers102

model:
  model_type: variational
  latent_dim: 128
  num_blocks: 4
  base_channels: 64
  num_encoder_resblocks: 1
  num_decoder_resblocks: 2

training:
  vae_type: beta
  epochs: 150
  learning_rate: 0.0001
  batch_size: 64
  beta: 0.5
  beta_start: 0.0
  beta_end: 0.5
  kl_warmup_epochs: 30
  lambda_perceptual: 1.0
  lambda_adversarial: 0.1
  adversarial_warmup_steps: 2000
  free_bits: 0.1

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt
