type: ae

dataset:
  name: flowers102
  channels: 3
  width: 64
  height: 64
  num_classes: 102

model:
  model_type: variational
  latent_dim: 128
  num_blocks: 3
  base_channels: 64

training:
  epochs: 150
  learning_rate: 0.0005
  batch_size: 64
  beta: 1.0
  kl_warmup_epochs: 20
  lambda_perceptual: 1.0
  lambda_adversarial: 0.1
  adversarial_warmup_steps: 2000
  free_bits: 0.5

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt