type: ae

dataset:
  name: flowers102

model:
  model_type: variational
  latent_dim: 128
  num_blocks: 4
  base_channels: 64
  num_encoder_resblocks: 1
  num_decoder_resblocks: 2

training:
  vae_type: tcvae
  epochs: 200
  learning_rate: 0.0001
  batch_size: 128
  beta: 1.0
  beta_start: 0.0
  beta_end: 1.0
  kl_warmup_epochs: 50
  tcvae_alpha: 1.0
  tcvae_beta: 6.0
  tcvae_gamma: 1.0
