type: ae

dataset:
  name: mnist
  channels: 3
  width: 28
  height: 28
  num_classes: 10

model:
  model_type: variational
  latent_dim: 16
  num_blocks: 2
  base_channels: 32

training:
  epochs: 1
  learning_rate: 0.0005
  batch_size: 256
  beta: 1.0
  kl_warmup_epochs: 10

wandb:
  mode: disabled
  project: master-thesis
  entity: jmartini-tu-darmstadt