type: ae

dataset:
  name: mnist

model:
  model_type: variational
  latent_dim: 8
  num_blocks: 2
  base_channels: 16

training:
  vae_type: beta
  epochs: 50
  learning_rate: 0.0005
  batch_size: 256
  beta: 4.0
  beta_start: 0.0
  beta_end: 4.0
  kl_warmup_epochs: 5

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt
