type: ae

dataset:
  name: mnist
  channels: 3
  width: 28
  height: 28
  num_classes: 10

model:
  model_type: variational
  latent_dim: 16
  base_channels: 32
  num_blocks: 2
  res_blocks: 0

training:
  epochs: 50
  learning_rate: 0.0005
  batch_size: 256
  beta: 8.0

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt