cspn:
  model_type: "custom"
  num_leaves: 16
  num_sums: 128
  depth: 3
  num_repetitions: 1
  nn_hidden_dim: 256
  nn_num_hidden_layers: 3

# TODO add pretrained section for autoencoder

dataset:
  name: cub200
  channels: 3
  width: 128
  height: 128
  num_classes: 200

training:
  epochs: 150
  learning_rate: 0.001
  batch_size: 32

wandb:
  mode: online
  project: master-thesis
  entity: jmartini-tu-darmstadt

paths:
  autoencoder: "checkpoints/autoencoder/cub200.pt"
  cspn: "checkpoints/cspn/cub_custom.pt"

seed: null
